version: '3'

services:
  flask-app:
    build: .
    ports:
     - "5000:5000"
    environment:
      - API_URL=API_URL

  nginx:
    image: nginx:latest
    ports:
     - "80:80"
    volumes:
     - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
     - flask-app
